"""empty message

Revision ID: 084b7a0d733b
Revises: 
Create Date: 2022-05-09 18:26:29.470010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '084b7a0d733b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weathers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Integer(), nullable=True),
    sa.Column('timess', sa.DateTime(), nullable=True),
    sa.Column('date_del', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weathers')
    # ### end Alembic commands ###
